Initial upload
husarion/rosbot-xl-nav-snap pull request #1
Opened 2023-09-19 17:06 UTC by artivis

2023-10-05 13:29 UTC, Kotochleb requested changes
Everything works fine. Aside of that small changes it is ok

2023-10-05 13:29 UTC, Kotochleb commented on README.md
> +- [rosbot-xl-teleop](https://snapcraft.io/rosbot-xl-teleop)
```suggestion
> **Note**
> This snap is part of an integrated snaps deployment.
> 
> Other recommended snaps to be installed are,
> 
> - [micro-xrce-dds-agent](LINK)
> - [sllidar-ros2](https://snapcraft.io/sllidar-ros2)
> - [rosbot-xl-teleop](https://snapcraft.io/rosbot-xl-teleop)
> - [rosbot-xl-nav](https://snapcraft.io/rosbot-xl-nav)
```

2023-10-05 13:29 UTC, Kotochleb commented on snap/snapcraft.yaml
> +    #   LD_LIBRARY_PATH: "$SNAP/opt/ros/underlay_ws/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/blas:$SNAP/opt/ros/underlay_ws/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/lapack"
This can be already removed

2023-10-05 13:29 UTC, Kotochleb commented on snap/hooks/configure
> +esac
```suggestion
case "$SIMULATION" in
	"True") ;;
	"False") ;;
	*)
		>&2 echo "'$SIMULATION' is not a supported value for simulation." \
      "Possible values are True, False"
	    logger -t ${SNAP_NAME} "'$SIMULATION' is not a supported value for simulation." \
      "Possible values are True, False"
		return 1
		;;
esac
```

2023-10-05 13:29 UTC, Kotochleb commented on snap/snapcraft.yaml
Separate app to save the map would be a nice addition

2023-10-05 13:29 UTC, Kotochleb commented on snap/local/mux_select_nav_vel.sh
> +$SNAP/opt/ros/underlay_ws/opt/ros/$ROS_DISTRO/bin/ros2 service call /mux/select topic_tools_interfaces/srv/MuxSelect "{topic: /nav_vel}"
```suggestion
ros2 service call /mux/select topic_tools_interfaces/srv/MuxSelect "{topic: /nav_vel}"
```
As far as I am concerned this is no longer required

2023-10-05 13:29 UTC, Kotochleb commented on snap/local/map_server_launcher.sh
This file is not used anywhere...

2023-10-05 13:29 UTC, Kotochleb commented on README.md
> +snap start rosbot-xl-teleop.slam
```suggestion
snap start rosbot-xl-nav.slam
```

2023-10-05 13:29 UTC, Kotochleb commented on README.md
> +snap stop rosbot-xl-teleop.slam
```suggestion
snap stop rosbot-xl-nav.slam
```

2023-10-05 13:29 UTC, Kotochleb commented on README.md
> +snap start rosbot-xl-teleop.localisation
```suggestion
snap start rosbot-xl-nav.localisation
```

2023-10-05 13:29 UTC, Kotochleb commented on README.md
> +snap stop rosbot-xl-teleop.localisation
```suggestion
snap stop rosbot-xl-nav.localisation
```

2023-10-05 13:29 UTC, Kotochleb commented on README.md
> +rosbot-xl-teleop.navigation
```suggestion
rosbot-xl-nav.navigation
```

2023-10-05 13:29 UTC, Kotochleb commented on README.md
> +network-bind         rosbot-xl:network-bind  :network-bind                   -
```suggestion
$ snap connections rosbot-xl-nav
Interface            Plug                        Slot                            Notes
content[ros-humble]  rosbot-xl-nav:ros-humble    ros-humble-ros-base:ros-humble  manual
network              rosbot-xl-nav:network       :network                        -
network-bind         rosbot-xl-nav:network-bind  :network-bind                   -

```

2023-10-05 13:29 UTC, Kotochleb commented on README.md
> +Upon stopping the application automatically save the map at `${SNAP_COMMON}/maps/current_map.{png,yaml}`.
```suggestion
Upon stopping the application automatically save the map at `$SNAP_COMMON/maps/current_map.{png,yaml}`.
```
Just to keep it coherent with all the rest

2023-10-06 12:28 UTC, artivis commented on snap/snapcraft.yaml
Let us iterate on that later ;)

2023-10-06 15:11 UTC, Kotochleb approved these changes
After all of the discussions, it looks and works good. I am closing this PR

2023-10-06 15:11 UTC, merged

2023-10-06 15:20 UTC, Guillaumebeuzeboc commented on README.md
> +snap start rosbot-xl-nav.slam
sudo is required to start/stop services